#################
# Build profile #
#################
[profile.default]
src  = "src"
out  = "out"
libs = ["lib"]
solc_version = "0.8.20"
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/"
]

###############################
# RPC endpoints & default net #
###############################
[rpc_endpoints]
base = "https://8453.rpc.thirdweb.com"
base_sepolia = "https://84532.rpc.thirdweb.com"

